# Generated by Django 4.2 on 2023-07-22 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clothes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='image',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='look',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
