# Generated by Django 4.2 on 2023-12-10 12:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_look_likes_delete_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='clothes',
            name='colour',
            field=models.CharField(blank=True, choices=[('wt', 'white'), ('gr', 'gray'), ('rd', 'red'), ('pk', 'pink'), ('or', 'orange'), ('yl', 'yellow'), ('lgn', 'light_green'), ('gn', 'green'), ('lbl', 'light_blue'), ('pr', 'purple'), ('br', 'brown'), ('bk', 'black')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='look',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='core.clothescategory'),
        ),
    ]
