# Generated by Django 4.2 on 2023-12-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clothescategory_alter_clothes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='look',
            name='clothes',
        ),
        migrations.AddField(
            model_name='clothescategory',
            name='look',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothes_category', to='core.look'),
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='category',
        ),
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.ManyToManyField(related_name='clothes', to='core.clothescategory'),
        ),
    ]
