# Generated by Django 4.2 on 2023-12-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_clothes_options_remove_look_clothes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='description',
        ),
    ]
