# Generated by Django 4.2 on 2023-04-30 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_clothes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.style'),
        ),
    ]
