# Generated by Django 4.2 on 2023-04-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_comment_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='link',
        ),
        migrations.CreateModel(
            name='ClothesLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='website.clothes')),
            ],
        ),
    ]
